### ISSUE TITLE
Provide Version info details

### ISSUE THREAD

**Issue by MacSplody** [MWSE/MWSE#236]
**Is your feature request related to a problem? Please describe.**
It's related to using version info to compare files for updates and compatibility in [LOOT's](https://loot.github.io/) Morrowind masterlist.

A few examples of how the version info of SKSE is used.

```yaml

# SKSE 64 - Latest Version
  - <<: *versionOldX
    subs: [ '**Script Extender ([SKSE 64](http://skse.silverlock.org))**' ]
    condition: 'version("../skse64_loader.exe", "0.2.0.16", <) and file("../SkyrimSE.exe") and file("../skse64_loader.exe")'
  - <<: *versionUpToDateX
    subs: [ '**Script Extender ([SKSE 64](http://skse.silverlock.org))**' ]
    condition: 'version("../skse64_loader.exe", "0.2.0.16", >=) and file("../SkyrimSE.exe") and file("../skse64_loader.exe")'

```
or
```yaml
# SKSE Plugins - Compatibility
  # Game Runtime
  - <<: *versionSksePluginIncSSE
    subs: [ '[DynDOLOD .DLL SSE](https://forum.step-project.com/topic/13716-dyndolod-dll/)' ]
    condition: 'file("SKSE/Plugins/DynDOLOD.DLL") and file("../skse64_loader.exe") and ((version("SKSE/Plugins/DynDOLOD.DLL", "1.5.73.0", ==) and product_version("../SkyrimSE.exe", "1.5.73.0", !=)) or (version("SKSE/Plugins/DynDOLOD.DLL", "1.5.73.0", <) and product_version("../SkyrimSE.exe", "1.5.73.0", ==)))'
```

**Describe the solution you'd like.**
For the current version or product version to be listed in the `MWSE.dll` properties.

**Describe alternatives you've considered.**
The alternative approach is to use CRC32 hash values for version comparision.
This is a lot harder to maintain and less accurate.

**Additional context.**

SKSE version info

![image](https://user-images.githubusercontent.com/1944639/66010169-b9dd1c80-e4b5-11e9-9cb9-d92678951e4a.png)
